-- Adicionar coluna modo_calculo na tabela produtos
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS modo_calculo TEXT NOT NULL DEFAULT 'grafica';

-- Tabela de configurações do usuário (persiste entre dispositivos)
CREATE TABLE IF NOT EXISTS user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL DEFAULT auth.uid(),
    settings_json JSONB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT unique_user_settings UNIQUE (user_id)
);

ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Usuário pode ver suas próprias configurações"
    ON user_settings FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Usuário pode inserir suas próprias configurações"
    ON user_settings FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Usuário pode atualizar suas próprias configurações"
    ON user_settings FOR UPDATE
    USING (auth.uid() = user_id);
